### ISSUE TITLE
Enhance UI

### ISSUE THREAD

**Issue by n00tn00tz** [n00tn00tz/kinematics-visualiser#10]
## Description
Improve user interface and experience

## Tasks
- [ ] Add responsive features and design 
- [ ] implement a dark mode
- [ ] Add tooltips and help text (research needs to be done for this)
- [ ] Save user preferences
- [ ] make the control layout better
