### ISSUE TITLE
Complete Technical Documentation

### ISSUE THREAD

**Issue by n00tn00tz** [n00tn00tz/kinematics-visualiser#11]
## Description
Create comprehensive technical documentation

## Tasks
- [ ] Document mathematical foundations 
- [ ] Make documentation for the API 
- [ ] Include tutorials and examples 
- [ ] Configuration options for documents 
- [ ] include a troubleshooting guide (maybe)
