### ISSUE TITLE
Implement joint control interface

### ISSUE THREAD

**Issue by n00tn00tz** [n00tn00tz/kinematics-visualiser#3]
## Description
Create the UI controls for manipulating robot arm joints

## Tasks
- [ ] Create slider controls for each joint
- [ ] Add angle display
- [ ] Implement real-time value updates
- [ ] Add joint limit indicators
- [ ] Create reset/home position button
