### ISSUE TITLE
Create real-time update system

### ISSUE THREAD

**Issue by n00tn00tz** [n00tn00tz/kinematics-visualiser#4]
## Description
Implement efficient update and rendering system

## Tasks
- [ ] Setup animation frame loop
- [ ] Implement efficient redraw system
- [ ] Add performance monitoring
- [ ] Create update throttling if needed
- [ ] Add FPS display  (if time permits)
