### ISSUE TITLE
Implement forward kinematics calculations

### ISSUE THREAD

**Issue by n00tn00tz** [n00tn00tz/kinematics-visualiser#5]
## Description
Create the core mathematics for forward kinematics

## Tasks
- [ ] Implement basic forward kinematics
- [ ] Add joint transformation calculations
- [ ] Create end-effector position calculation
- [ ] Add position validation
- [ ] Implement joint limit checks

## Technical Details
- Consider using matrix operations for transformations
- Implement proper angle conventions
- Add error handling for invalid configurations
