### ISSUE TITLE
Add Basic Project Documentation

### ISSUE THREAD

**Issue by n00tn00tz** [n00tn00tz/kinematics-visualiser#6]
## Description
Create initial documentation covering setup and basic usage

## Tasks
- [ ] Create project README
- [ ] Document installation steps
- [ ] Add basic usage guide
- [ ] Document component structure
- [ ] Add inline code documentation
