### ISSUE TITLE
Add Workplace Visualisation

### ISSUE THREAD

**Issue by n00tn00tz** [n00tn00tz/kinematics-visualiser#9]
## Description
Implement workspace analysis and visualisation tools

## Tasks
- [ ] Determine the bounds of the workspace 
- [ ] Include a visualisation of reachability 
- [ ] Put workspace metrics into practice 
- [ ] Incorporate interactive workspace exploration in your work.
- [ ] Provide a feature for workspace exportation (maybe)
